# !/usr/bin/env python
# -*-coding:utf-8 -*-

"""
  Author  ：lining
  Email  ：993811091@qq.com
  Time  ：2023/3/20
  Desc  ：比较从集合中判断和从列表中判断的差异
"""
import functools
import time

result = [{"query": "被美军炸了67次又遇上日本核污水", "score": 0.45771439583889495, "flag": 1, "topic_flag": 1, "hot": 360646,
           "description": 361415, "is_hot_top": 1, "ori_pos": 1, "cate": ["社会新闻"], "sub_category": [""],
           "star_name": [], "event_name": [], "channel_type": ["1_社会", "3_商业媒体主持"],
           "generate_keys": [["grade", "A", 1]], "limit_position": 1, "recommend_type": 2, "recommended_position": 26,
           "guaranteed_level": 100, "final_pos": 1, "hot_ext": "vcnt:1", "social_flag": 0, "social_tag": 1,
           "reasons": [], "source_details": "s0k12:s7k11:s1k0:gra_A:o_1:rty_2:rpo_26:lpo_1:fpo_1"},
          {"query": "武林外传官方诉浙江广电", "score": 0.328148535, "flag": 1, "topic_flag": 1, "hot": 1490795,
           "description": 1381347, "ori_pos": 2, "cate": ["艺人"], "sub_category": ["艺人", "艺人新闻"], "star_name": [],
           "event_name": [], "channel_type": ["1_文娱"], "generate_keys": [["grade", "A", 1], ["redis_top_pos", 1, 2]],
           "limit_position": 2, "recommend_type": 2, "recommended_position": 5, "guaranteed_level": 51, "final_pos": 2,
           "hot_ext": "vcnt:1", "social_flag": 0, "social_tag": 4, "reasons": [],
           "source_details": "s0k12:s7k11:s1k0:gra_A:o_2:rty_2:rpo_5:lpo_2:fpo_2"},
          {"query": "福岛真相", "score": 0.25444112, "flag": 16, "topic_flag": 1, "hot": 3935189, "description": "09:52登顶",
           "ori_pos": 3, "cate": ["社会新闻"], "sub_category": [""], "star_name": [], "event_name": [],
           "channel_type": ["1_社会", "3_央媒主持", "3_权威媒体主持"], "generate_keys": [["grade", "A", 1], ["channel", 35]],
           "limit_position": 1, "final_pos": 3, "hot_ext": "vcnt:1", "source_flag": "1", "social_flag": 0,
           "social_tag": 1, "reasons": [], "source_details": "s0k12:s7k11:s1k0:gra_A:o_3:lpo_1:fpo_3"},
          {"query": "金城武 我很讨厌在拍戏时看到动物", "score": 0.12153498, "flag": 2, "topic_flag": 0, "hot": 2535903,
           "description": "10:32登顶",
           "generate_keys": [["position_adjustment", 0.44], ["grade", "A", 1], ["hot_top10_keep", 710],
                             ["keep_Enter", 710]], "ori_pos": 4, "cate": ["作品衍生"], "sub_category": ["作品衍生", "作品周边"],
           "star_name": [], "event_name": [], "channel_type": ["1_文娱", "3_单条", "4_单条生活消遣"], "limit_position": 1,
           "recommend_type": 2, "recommended_position": 30, "guaranteed_level": 100, "ctg_control_type_list": [710],
           "category_control_type": 710, "right_position": 8, "final_pos": 4, "hot_ext": "vcnt:1", "source_flag": "1",
           "social_flag": 0, "social_tag": 4, "reasons": [],
           "source_details": "s0k12:s7k11:s1k0:pa_0.4:gra_A:kp_e_710:o_4:rty_2:rpo_30:lpo_1:fpo_4"},
          {"query": "杜海涛几十年的主持人白干了", "score": 0.19767524, "flag": 1, "topic_flag": 1, "hot": 1039446,
           "description": "好友正在看", "ori_pos": 5, "cate": ["综艺"], "sub_category": ["综艺", "明星综艺"], "star_name": ["杜海涛"],
           "event_name": [], "channel_type": ["1_文娱"],
           "generate_keys": [["grade", "A", 1], ["hot_top10_keep", 710], ["keep_Enter", 710]], "limit_position": 1,
           "recommend_type": 2, "recommended_position": 29, "guaranteed_level": 100, "ctg_control_type_list": [710],
           "category_control_type": 710, "right_position": 9, "final_pos": 5, "hot_ext": "vcnt:1", "social_flag": 0,
           "reasons": [], "source_details": "s0k12:s7k11:s1k0:gra_A:kp_e_710:o_5:rty_2:rpo_29:lpo_1:fpo_5"},
          {"query": "北京周末阵雨或雷阵雨频繁", "source_flag": "9", "flag": 8, "topic_flag": 0, "city_code": "800861100",
           "ori_pos": 7, "cate": [], "sub_category": [], "star_name": [], "event_name": [], "channel_type": [],
           "limit_position": 21, "recommend_type": 1, "fixed_position": 6, "guaranteed_level": 4, "final_pos": 6,
           "hot_ext": "vcnt:1", "description": "北京", "social_flag": 0, "reasons": [],
           "source_details": "-1:o_7:rty_1:lpo_21:fpo_6:fix_6"},
          {"query": "日本渔民哭诉政府愚蠢导致无法生存", "score": 0.08154822, "flag": 1, "topic_flag": 1, "hot": 357413,
           "description": 356895, "ori_pos": 17, "cate": ["社会新闻"], "sub_category": [""], "star_name": [],
           "event_name": [], "channel_type": ["1_社会", "3_商业媒体主持"],
           "generate_keys": [["grade", "A", 1], ["redis_top_pos", 1, 4]], "limit_position": 4, "final_pos": 7,
           "hot_ext": "vcnt:1", "social_flag": 0, "social_tag": 1, "reasons": [],
           "source_details": "s1k0:gra_A:o_17:lpo_4:fpo_7"},
          {"query": "安妮海瑟薇的颜值变化", "score": 0.07494288, "flag": 2, "topic_flag": 0, "hot": 667909, "description": "上午霸榜",
           "ori_pos": 20, "cate": ["作品衍生"], "sub_category": ["作品衍生", "作品造型"], "star_name": ["安妮海瑟薇"], "event_name": [],
           "channel_type": ["1_文娱", "2_时尚美妆2", "3_单条", "4_单条视频作品"],
           "generate_keys": [["grade", "A", 1], ["redis_top_pos", 1, 2], ["toplimit_Enter", 803],
                             ["hot_top10_keep", 710], ["film_festival", 55], ["channel_extra_hold_3_单条", 20, 20]],
           "limit_position": 2, "ctg_control_type_list": [803, 710], "category_control_type": 710, "right_position": 10,
           "final_pos": 8, "hot_ext": "vcnt:1", "source_flag": "1", "social_flag": 0, "social_tag": 4, "reasons": [],
           "source_details": "s0k12:s1k0:gra_A:tl_e_803:filmfestival_55:o_20:lpo_2:fpo_8"},
          {"query": "央视莲花楼剪辑顺序换了", "score": 0.07505461, "flag": 0, "topic_flag": 1, "hot": 84606, "description": 154484,
           "ori_pos": 19, "cate": ["影视"], "sub_category": ["影视", "影视作品"], "star_name": [], "event_name": [],
           "channel_type": ["1_文娱"], "generate_keys": [["grade", "A", 1], ["redis_top_pos", 1, 4]], "limit_position": 4,
           "final_pos": 9, "hot_ext": "vcnt:1", "social_flag": 0, "reasons": [],
           "source_details": "s1k0:gra_A:o_19:lpo_4:fpo_9"},
          {"query": "郑恺女儿上综艺了", "score": 0.05120774, "flag": 2, "topic_flag": 1, "hot": 1265133,
           "description": "08:04登顶",
           "generate_keys": [["position_adjustment", 0.35], ["grade", "A", 1], ["toplimit_Enter", 803]], "ori_pos": 24,
           "cate": ["综艺"], "sub_category": ["综艺", "明星综艺"], "star_name": ["郑恺"], "event_name": [],
           "channel_type": ["1_文娱"], "limit_position": 1, "ctg_control_type_list": [803], "category_control_type": 803,
           "final_pos": 10, "hot_ext": "vcnt:1", "source_flag": "1", "social_flag": 0, "social_tag": 4, "reasons": [],
           "source_details": "s0k12:s1k0:pa_0.3:gra_A:tl_e_803:o_24:lpo_1:fpo_10"},
          {"query": "核辐射检测仪卖爆了", "score": 0.11923265999999999, "flag": 1, "topic_flag": 1, "hot": 287819,
           "description": 293180, "ori_pos": 9, "cate": ["社会新闻"], "sub_category": [""], "star_name": [],
           "event_name": [], "channel_type": ["1_社会", "3_央媒主持", "3_权威媒体主持"],
           "generate_keys": [["grade", "C", 1], ["channel", 60]], "limit_position": 11, "final_pos": 11,
           "hot_ext": "vcnt:1", "social_flag": 0, "social_tag": 1, "reasons": [],
           "source_details": "s0k12:s1k0:gra_C:o_9:lpo_11:fpo_11"},
          {"query": "如何看待国庆中秋上7休8", "score": 0.0913700655, "flag": 1, "topic_flag": 1, "hot": 196434,
           "description": 184786, "ori_pos": 13, "cate": ["社会议题"], "sub_category": [""], "star_name": [],
           "event_name": [], "channel_type": ["1_社会", "3_投票", "3_商业媒体主持"], "generate_keys": [["grade", "C", 1]],
           "limit_position": 11, "final_pos": 12, "hot_ext": "vcnt:1", "social_flag": 0, "social_tag": 1, "reasons": [],
           "source_details": "s0k12:s1k0:gra_C:o_13:lpo_11:fpo_12"},
          {"query": "江苏常州一隧道口发生惨烈车祸", "score": 0.090839776245, "flag": 0, "topic_flag": 1, "hot": 880233,
           "description": 88615,
           "generate_keys": [["expose_reduce", 0.6245, 7, [7, 5, 13]], ["grade", "A", 1], ["redis_top_pos", 1, 11],
                             ["channel", 60]], "ori_pos": 14, "cate": ["社会新闻"], "sub_category": [""], "star_name": [],
           "event_name": [], "channel_type": ["1_社会", "3_央媒主持", "3_权威媒体主持"], "limit_position": 11, "final_pos": 13,
           "hot_ext": "vcnt:1", "social_flag": 0, "social_tag": 4, "reasons": [],
           "source_details": "s0k12:s1k0:gra_A:o_14:lpo_11:fpo_13"},
          {"query": "这段视频也火到国外去了", "score": 0.09064678, "flag": 0, "topic_flag": 0, "hot": 261906,
           "description": 263303, "ori_pos": 15, "cate": ["情感"], "sub_category": [""], "star_name": [],
           "event_name": [], "channel_type": ["1_垂类", "1_重点垂类", "2_情感幽默", "3_单条", "4_单条生活消遣"],
           "generate_keys": [["grade", "C", 1]], "limit_position": 11, "final_pos": 14, "hot_ext": "vcnt:1",
           "social_flag": 0, "social_tag": 4, "reasons": [], "source_details": "s0k12:s1k0:gra_C:o_15:lpo_11:fpo_14"},
          {"query": "到学校了发现还连着家里的WiFi", "score": 0.06572508, "flag": 0, "topic_flag": 0, "hot": 248711,
           "description": 250568, "ori_pos": 27, "cate": ["幽默"], "sub_category": [""], "star_name": [],
           "event_name": [], "channel_type": ["1_垂类", "1_重点垂类", "2_情感幽默", "3_单条", "4_单条生活消遣"],
           "generate_keys": [["grade", "C", 1], ["channel_extra_hold_3_单条", 27, 20]], "limit_position": 11,
           "final_pos": 15, "hot_ext": "vcnt:1", "social_flag": 0, "reasons": [],
           "source_details": "s1k0:gra_C:o_27:lpo_11:fpo_15"},
          {"query": "封神票房", "score": 0.06984558, "flag": 0, "topic_flag": 0, "hot": 77990, "description": "上午霸榜",
           "ori_pos": 21, "cate": ["影视"], "sub_category": ["影视", "影视作品"], "star_name": [], "event_name": [],
           "channel_type": ["1_文娱"], "generate_keys": [["grade", "A", 1], ["redis_top_pos", 1, 11]],
           "limit_position": 11, "final_pos": 16, "hot_ext": "vcnt:1", "source_flag": "1", "social_flag": 0,
           "social_tag": 3, "reasons": [], "source_details": "s0k12:s1k0:gra_A:o_21:lpo_11:fpo_16"},
          {"query": "林志颖曾开记者会官宣当爸", "score": 0.051538188, "flag": 1, "topic_flag": 1, "hot": 512573,
           "description": 514702,
           "generate_keys": [["position_adjustment", 0.33], ["grade", "A", 1], ["toplimit_Enter", 803]], "ori_pos": 25,
           "cate": ["艺人"], "sub_category": ["艺人", "艺人琐事"], "star_name": ["仲天骐", "林志颖"], "event_name": [],
           "channel_type": ["1_文娱"], "limit_position": 1, "ctg_control_type_list": [803], "category_control_type": 803,
           "final_pos": 17, "hot_ext": "vcnt:1", "social_flag": 0, "reasons": [],
           "source_details": "s0k12:s1k0:pa_0.3:gra_A:tl_e_803:o_25:lpo_1:fpo_17"},
          {"query": "高铁上一女子被母女俩吵醒双方互殴", "score": 0.06782554, "flag": 0, "topic_flag": 1, "hot": 264675,
           "description": "好友正在看", "ori_pos": 26, "cate": ["社会新闻"], "sub_category": [""], "star_name": [],
           "event_name": [], "channel_type": ["1_社会", "3_商业媒体主持"], "generate_keys": [["grade", "C", 1]],
           "limit_position": 11, "final_pos": 18, "hot_ext": "vcnt:1", "social_flag": 0, "social_tag": 1, "reasons": [],
           "source_details": "s0k12:s1k0:gra_C:o_26:lpo_11:fpo_18"},
          {"query": "女孩疑早恋和母亲吵架跳河男孩营救溺亡", "score": 0.039343413, "flag": 2, "topic_flag": 1, "hot": 289845,
           "description": 295831, "ori_pos": 68, "cate": ["社会新闻"], "sub_category": [""], "star_name": [],
           "event_name": [], "channel_type": ["1_社会", "3_商业媒体主持"],
           "generate_keys": [["grade", "C", 1], ["hot_top10_keep", 720]], "limit_position": 11,
           "ctg_control_type_list": [720], "category_control_type": 720, "right_position": 19, "final_pos": 19,
           "hot_ext": "vcnt:1", "social_flag": 0, "social_tag": 1, "reasons": [],
           "source_details": "s0k12:s1k0:gra_C:o_68:lpo_11:fpo_19"},
          {"query": "超强台风苏拉", "score": 0.06304804, "flag": 1, "topic_flag": 1, "hot": 284429, "description": "好友正在看",
           "ori_pos": 28, "cate": ["社会新闻"], "sub_category": [""], "star_name": [], "event_name": [],
           "channel_type": ["1_社会", "3_权威媒体主持"], "generate_keys": [["grade", "C", 1]], "limit_position": 11,
           "final_pos": 20, "hot_ext": "vcnt:1", "social_flag": 0, "reasons": [],
           "source_details": "s1k0:gra_C:o_28:lpo_11:fpo_20"},
          {"query": "胡锡进 日本驻华使馆是否在挑拨", "score": 0.165411, "flag": 0, "topic_flag": 1, "hot": 363873,
           "description": 58832, "ori_pos": 8, "cate": ["国内要闻"], "sub_category": [""], "star_name": [],
           "event_name": [], "channel_type": ["1_社会", "3_单条", "4_单条垂直专业内容"], "generate_keys": [["grade", "A", 21]],
           "limit_position": 21, "final_pos": 21, "hot_ext": "vcnt:1", "social_flag": 0, "social_tag": 2, "reasons": [],
           "source_details": "s1k0:gra_A:o_8:lpo_21:fpo_21"},
          {"query": "内裤不要反着晒", "score": 0.114785336, "flag": 32, "topic_flag": 1, "hot": 692120, "description": 51569,
           "ori_pos": 10, "cate": ["情感"], "sub_category": [""], "star_name": [], "event_name": [],
           "channel_type": ["1_垂类", "1_重点垂类", "2_情感幽默"], "generate_keys": [["grade", "C", 21]], "limit_position": 21,
           "final_pos": 22, "hot_ext": "vcnt:1", "social_flag": 0, "reasons": [],
           "source_details": "s1k0:gra_C:o_10:lpo_21:fpo_22"},
          {"query": "邓为 我觉得火不敢当", "score": 0.10109274900000001, "flag": 0, "topic_flag": 0, "hot": 27725,
           "description": 51026, "ori_pos": 12, "cate": ["影视"], "sub_category": ["影视", "明星影视"], "star_name": ["邓为"],
           "event_name": [], "channel_type": ["1_文娱"], "generate_keys": [["grade", "C", 1], ["redis_top_pos", 11, 21]],
           "limit_position": 21, "final_pos": 23, "hot_ext": "vcnt:1", "social_flag": 0, "reasons": [],
           "source_details": "s1k0:gra_C:o_12:lpo_21:fpo_23"},
          {"query": "第一次见拔箭如此干脆的女主", "score": 0.055884283, "flag": 0, "topic_flag": 0, "hot": 358481,
           "description": "上午霸榜", "ori_pos": 34, "cate": ["影视"], "sub_category": ["影视", "影视作品"], "star_name": [],
           "event_name": [], "channel_type": ["1_文娱", "3_单条", "4_单条视频作品"],
           "generate_keys": [["grade", "A", 1], ["redis_top_pos", 1, 4], ["toplimit_Enter", 810],
                             ["channel_extra_hold_3_单条", 34, 30]], "limit_position": 4, "ctg_control_type_list": [810],
           "category_control_type": 810, "final_pos": 24, "hot_ext": "vcnt:1", "source_flag": "1", "social_flag": 0,
           "social_tag": 4, "reasons": [], "source_details": "s0k12:s1k0:gra_A:tl_e_810:o_34:lpo_4:fpo_24"},
          {"query": "芯片坏了要怎么换", "score": 0.05411356, "flag": 0, "topic_flag": 0, "hot": 538522, "description": "好友正在看",
           "ori_pos": 36, "cate": ["科技"], "sub_category": [""], "star_name": [], "event_name": [],
           "channel_type": ["1_垂类", "3_单条", "4_单条视频作品"],
           "generate_keys": [["grade", "A", 21], ["channel_extra_hold_3_单条", 36, 30]], "limit_position": 21,
           "final_pos": 25, "hot_ext": "vcnt:1", "social_flag": 0, "reasons": [],
           "source_details": "s1k0:gra_A:o_36:lpo_21:fpo_25"},
          {"query": "孙俪写100遍隶书心经用了三年", "score": 0.061397024999999994, "flag": 1, "topic_flag": 1, "hot": 264202,
           "description": 272154, "ori_pos": 29, "cate": ["艺人"], "sub_category": ["艺人", "艺人分享"], "star_name": ["孙俪"],
           "event_name": [], "channel_type": ["1_文娱"],
           "generate_keys": [["grade", "A", 1], ["redis_top_pos", 1, 4], ["toplimit_Enter", 810]], "limit_position": 4,
           "ctg_control_type_list": [810], "category_control_type": 810, "final_pos": 26, "hot_ext": "vcnt:1",
           "social_flag": 0, "reasons": [], "source_details": "s1k0:s6k8:gra_A:tl_e_810:o_29:lpo_4:fpo_26"},
          {"query": "我们找了几个美国人聊核污染水", "score": 0.053657614, "flag": 0, "topic_flag": 0, "hot": 847899,
           "description": 51381, "ori_pos": 37, "cate": ["社会新闻"], "sub_category": [""], "star_name": [],
           "event_name": [], "channel_type": ["1_社会", "3_单条", "4_单条视频作品"], "generate_keys": [["grade", "A", 21]],
           "limit_position": 21, "final_pos": 27, "hot_ext": "vcnt:1", "social_flag": 0, "reasons": [],
           "source_details": "s1k0:gra_A:o_37:lpo_21:fpo_27"},
          {"query": "中卫沙漠公路", "score": 0.052990206, "flag": 0, "topic_flag": 0, "hot": 545075, "description": 19600,
           "ori_pos": 38, "cate": ["旅游"], "sub_category": [""], "star_name": [], "event_name": [],
           "channel_type": ["1_垂类", "1_重点垂类", "3_单条", "4_单条生活消遣"], "generate_keys": [["grade", "C", 21]],
           "limit_position": 21, "final_pos": 28, "hot_ext": "vcnt:1", "social_flag": 0, "reasons": [],
           "source_details": "s1k0:gra_C:o_38:lpo_21:fpo_28"},
          {"query": "我的英语老师改行造显微镜去了", "score": 0.05206898, "flag": 32768, "topic_flag": 1, "hot": 139407,
           "description": "好友正在看", "ori_pos": 39, "cate": ["幽默"], "sub_category": [""], "star_name": [],
           "event_name": [], "channel_type": ["1_垂类", "1_重点垂类", "2_情感幽默", "3_暖新闻", "3_权威媒体主持"],
           "generate_keys": [["grade", "A", 1], ["redis_top_pos", 1, 11]], "limit_position": 11, "final_pos": 29,
           "hot_ext": "vcnt:1", "social_flag": 0, "reasons": [], "source_details": "s1k0:gra_A:o_39:lpo_11:fpo_29"},
          {"query": "五月天演唱会最大的受害者", "score": 0.048887268, "flag": 32, "topic_flag": 1, "hot": 260168,
           "description": 83167, "ori_pos": 42, "cate": ["音乐"], "sub_category": ["音乐", "明星音乐"], "star_name": ["五月天"],
           "event_name": [], "channel_type": ["1_文娱"], "generate_keys": [["grade", "C", 21]], "limit_position": 21,
           "final_pos": 30, "hot_ext": "vcnt:1", "social_flag": 0, "reasons": [],
           "source_details": "s0k12:s1k0:gra_C:o_42:lpo_21:fpo_30"},
          {"query": "谢长廷声称微量的放射性元素有益", "score": 0.08365891, "flag": 0, "topic_flag": 1, "hot": 990181,
           "description": 96472, "ori_pos": 16, "cate": ["社会新闻"], "sub_category": [""], "star_name": [],
           "event_name": [], "channel_type": ["1_社会", "3_央媒主持", "3_权威媒体主持"], "generate_keys": [["grade", "D", 21]],
           "limit_position": 31, "final_pos": 31, "hot_ext": "vcnt:1", "social_flag": 0, "social_tag": 1, "reasons": [],
           "source_details": "s0k12:s1k0:gra_D:o_16:lpo_31:fpo_31"},
          {"query": "曾舜晞把李雪琴整害羞了", "score": 0.1062083025, "flag": 0, "topic_flag": 1, "hot": 269352,
           "description": 54318, "ori_pos": 11, "cate": ["综艺"], "sub_category": ["综艺", "明星综艺"],
           "star_name": ["李雪琴", "曾舜晞"], "event_name": [], "channel_type": ["1_文娱"],
           "generate_keys": [["grade", "C", 1], ["redis_top_pos", 11, 21], ["recommender_split", "same_cluster"]],
           "limit_position": 21, "final_pos": 32, "hot_ext": "vcnt:1", "social_flag": 0, "reasons": [],
           "source_details": "s1k0:gra_C:sp_same_cluster:o_11:lpo_21:fpo_32"},
          {"query": "25岁特等功臣连老兵救人牺牲", "score": 0.057475902, "flag": 0, "topic_flag": 1, "hot": 804294,
           "description": 32537, "ori_pos": 30, "cate": ["社会新闻"], "sub_category": [""], "star_name": [],
           "event_name": [], "channel_type": ["1_社会", "3_央媒主持", "3_权威媒体主持"], "generate_keys": [["grade", "D", 21]],
           "limit_position": 31, "final_pos": 33, "hot_ext": "vcnt:1", "social_flag": 0, "reasons": [],
           "source_details": "s1k0:gra_D:o_30:lpo_31:fpo_33"},
          {"query": "餐饮店员工用自来水勾兑饮料给顾客饮用", "score": 0.04922835, "flag": 32, "topic_flag": 1, "hot": 336414,
           "description": 117361, "ori_pos": 40, "cate": ["社会新闻"], "sub_category": [""], "star_name": [],
           "event_name": [], "channel_type": ["1_社会", "3_权威媒体主持"], "generate_keys": [["grade", "D", 21]],
           "limit_position": 31, "final_pos": 34, "hot_ext": "vcnt:1", "social_flag": 0, "reasons": [],
           "source_details": "s1k0:gra_D:o_40:lpo_31:fpo_34"},
          {"query": "现实中的缅北诈骗远比电影惨烈", "score": 0.047304783, "flag": 1, "topic_flag": 1, "hot": 422020,
           "description": 418320, "ori_pos": 44, "cate": ["社会新闻"], "sub_category": [""], "star_name": [],
           "event_name": [], "channel_type": ["1_社会", "3_央媒主持", "3_权威媒体主持"],
           "generate_keys": [["grade", "A", 1], ["redis_top_pos", 1, 4], ["channel", 45]], "limit_position": 4,
           "final_pos": 35, "hot_ext": "vcnt:1", "social_flag": 0, "social_tag": 1, "reasons": [],
           "source_details": "s1k0:gra_A:o_44:lpo_4:fpo_35"},
          {"query": "东北阿姨有多能说", "score": 0.046969477, "flag": 0, "topic_flag": 1, "hot": 155057, "description": 14559,
           "ori_pos": 45, "cate": ["幽默"], "sub_category": [""], "star_name": [], "event_name": [],
           "channel_type": ["1_垂类", "1_重点垂类", "2_情感幽默"], "generate_keys": [["grade", "D", 21]], "limit_position": 31,
           "final_pos": 36, "hot_ext": "vcnt:1", "social_flag": 0, "reasons": [],
           "source_details": "s1k0:gra_D:o_45:lpo_31:fpo_36"},
          {"query": "iPhone15系列有三大重要变化", "score": 0.046689715, "flag": 0, "topic_flag": 1, "hot": 977921,
           "description": 87170, "ori_pos": 46, "cate": ["科技"], "sub_category": [""], "star_name": [], "event_name": [],
           "channel_type": ["1_垂类", "3_商业媒体主持"], "generate_keys": [["grade", "C", 21]], "limit_position": 21,
           "final_pos": 37, "hot_ext": "vcnt:1", "social_flag": 0, "reasons": [],
           "source_details": "s0k12:s1k0:gra_C:o_46:lpo_21:fpo_37"},
          {"query": "老人留下一套房产五兄妹和和气气均分", "score": 0.0448759903563, "flag": 32768, "topic_flag": 1, "hot": 337627,
           "description": 341544, "generate_keys": [["expose_reduce", 0.8819, 44, [2]], ["grade", "A", 1]],
           "ori_pos": 47, "cate": ["社会新闻"], "sub_category": [""], "star_name": [], "event_name": [],
           "channel_type": ["1_社会", "3_暖新闻", "3_权威媒体主持"], "limit_position": 1, "final_pos": 38, "hot_ext": "vcnt:1",
           "social_flag": 0, "social_tag": 4, "reasons": [], "source_details": "s0k12:s1k0:gra_A:o_47:lpo_1:fpo_38"},
          {"query": "世界上最小的相机", "score": 0.0442384, "flag": 32, "topic_flag": 0, "hot": 430779, "description": 56728,
           "ori_pos": 50, "cate": ["科技"], "sub_category": [""], "star_name": [], "event_name": [],
           "channel_type": ["1_垂类", "3_单条", "4_单条垂直专业内容"],
           "generate_keys": [["grade", "A", 21], ["channel_extra_hold_3_单条", 50, 50]], "limit_position": 21,
           "final_pos": 39, "hot_ext": "vcnt:1", "social_flag": 0, "reasons": [],
           "source_details": "s1k0:gra_A:o_50:lpo_21:fpo_39"},
          {"query": "搜狐视频舞蹈翻跳大赛", "source_flag": "8", "id": 200704, "ori_pos": 41, "cate": ["作品衍生"],
           "sub_category": ["作品衍生", "作品周边"], "star_name": [], "event_name": [],
           "channel_type": ["1_文娱", "3_央媒主持", "3_权威媒体主持"],
           "generate_keys": [["grade", "B", 1], ["redis_top_pos", 4, 21]], "limit_position": 21, "recommend_type": 1,
           "fixed_position": 40, "guaranteed_level": 3, "final_pos": 40, "topic_flag": 1, "hot_ext": "vcnt:1",
           "flag": 0, "description": 184657, "social_flag": 0, "reasons": [],
           "source_details": "s6k8:gra_B:o_41:rty_1:lpo_21:fpo_40:fix_40"},
          {"query": "以为自己给鬼压床了", "score": 0.043086022, "flag": 0, "topic_flag": 0, "hot": 759930, "description": 53457,
           "ori_pos": 52, "cate": ["幽默"], "sub_category": [""], "star_name": [], "event_name": [],
           "channel_type": ["1_垂类", "1_重点垂类", "2_情感幽默", "3_单条", "4_单条生活消遣"],
           "generate_keys": [["grade", "C", 21], ["channel_extra_hold_3_单条", 52, 50]], "limit_position": 21,
           "final_pos": 41, "hot_ext": "vcnt:1", "social_flag": 0, "reasons": [],
           "source_details": "s1k0:gra_C:o_52:lpo_21:fpo_41"},
          {"query": "光汉牛肉面", "score": 0.042925227, "flag": 0, "topic_flag": 0, "hot": 124997, "description": 37747,
           "ori_pos": 53, "cate": ["美食"], "sub_category": [""], "star_name": [], "event_name": [],
           "channel_type": ["1_垂类", "1_重点垂类", "3_单条", "4_单条生活消遣"],
           "generate_keys": [["grade", "A", 21], ["channel_extra_hold_3_单条", 53, 50]], "limit_position": 21,
           "final_pos": 42, "hot_ext": "vcnt:1", "social_flag": 0, "reasons": [],
           "source_details": "s1k0:gra_A:o_53:lpo_21:fpo_42"},
          {"query": "刘雨昕胸震", "score": 0.044595096, "flag": 0, "topic_flag": 1, "hot": 292611, "description": 300349,
           "ori_pos": 48, "cate": ["音乐"], "sub_category": ["音乐", "明星音乐"], "star_name": ["刘雨昕"], "event_name": [],
           "channel_type": ["1_文娱"], "generate_keys": [["grade", "C", 1]], "limit_position": 11, "final_pos": 43,
           "hot_ext": "vcnt:1", "social_flag": 0, "social_tag": 4, "reasons": [],
           "source_details": "s0k12:s1k0:gra_C:o_48:lpo_11:fpo_43"},
          {"query": "中秋可以连休8天", "score": 0.044448383, "flag": 0, "topic_flag": 1, "hot": 272550, "description": 275133,
           "ori_pos": 49, "cate": ["社会新闻"], "sub_category": [""], "star_name": [], "event_name": [],
           "channel_type": ["1_社会", "3_商业媒体主持"], "generate_keys": [["grade", "C", 1]], "limit_position": 11,
           "final_pos": 44, "hot_ext": "vcnt:1", "social_flag": 0, "social_tag": 1, "reasons": [],
           "source_details": "s0k12:s1k0:gra_C:o_49:lpo_11:fpo_44"},
          {"query": "学爸预测票房超6亿", "score": 0.044222545, "flag": 0, "topic_flag": 1, "hot": 826488, "description": 31383,
           "ori_pos": 51, "cate": ["影视"], "sub_category": ["影视", "影视作品"], "star_name": [], "event_name": [],
           "channel_type": ["1_文娱"], "generate_keys": [["grade", "C", 21]], "limit_position": 21, "final_pos": 45,
           "hot_ext": "vcnt:1", "social_flag": 0, "reasons": [], "source_details": "s1k0:gra_C:o_51:lpo_21:fpo_45"},
          {"query": "起猛了看见金熊猫了", "score": 0.042571113, "flag": 0, "topic_flag": 1, "hot": 166370, "description": 130196,
           "ori_pos": 55, "cate": ["社会新闻"], "sub_category": [""], "star_name": [], "event_name": [],
           "channel_type": ["1_社会", "3_权威媒体主持"], "generate_keys": [["grade", "D", 21]], "limit_position": 31,
           "final_pos": 46, "hot_ext": "vcnt:1", "social_flag": 0, "social_tag": 3, "reasons": [],
           "source_details": "s1k0:gra_D:o_55:lpo_31:fpo_46"},
          {"query": "新中式裙子", "score": 0.04242868, "flag": 0, "topic_flag": 0, "hot": 362094, "description": 362997,
           "ori_pos": 56, "cate": ["时尚"], "sub_category": [""], "star_name": [], "event_name": [],
           "channel_type": ["1_垂类", "1_重点垂类", "2_时尚美妆", "2_时尚美妆2", "3_单条", "4_单条视频作品"],
           "generate_keys": [["grade", "A", 1], ["redis_top_pos", 1, 2], ["film_festival", 60]], "limit_position": 2,
           "final_pos": 47, "hot_ext": "vcnt:1", "social_flag": 0, "social_tag": 4, "reasons": [],
           "source_details": "s0k12:s1k0:gra_A:filmfestival_60:o_56:lpo_2:fpo_47"},
          {"query": "10省份局地将有大到暴雨", "score": 0.0682378, "flag": 0, "topic_flag": 1, "hot": 839381, "description": 9220,
           "ori_pos": 23, "cate": ["社会新闻"], "sub_category": [""], "star_name": [], "event_name": [],
           "channel_type": ["1_社会", "3_央媒主持", "3_权威媒体主持"],
           "generate_keys": [["grade", "D", 21], ["recommender_split", "same_cluster"]], "limit_position": 31,
           "final_pos": 48, "hot_ext": "vcnt:1", "social_flag": 0, "social_tag": 1, "reasons": [],
           "source_details": "s1k0:gra_D:sp_same_cluster:o_23:lpo_31:fpo_48"},
          {"query": "大张伟谈早年遭遇", "score": 0.042342667, "flag": 0, "topic_flag": 1, "hot": 659281, "description": 22197,
           "ori_pos": 57, "cate": ["综艺"], "sub_category": ["综艺", "明星综艺"], "star_name": ["大张伟"], "event_name": [],
           "channel_type": ["1_文娱"],
           "generate_keys": [["grade", "A", 1], ["top10_hot_limit", 11], ["redis_top_pos", 11, 21]],
           "limit_position": 21, "final_pos": 49, "hot_ext": "vcnt:1", "social_flag": 0, "social_tag": 4, "reasons": [],
           "source_details": "s0k12:s1k0:gra_A:o_57:lpo_21:fpo_49"},
          {"query": "四川人小时候专属来电声音", "score": 0.04226566, "flag": 0, "topic_flag": 1, "hot": 718300,
           "description": 17661, "ori_pos": 58, "cate": ["情感"], "sub_category": [""], "star_name": [], "event_name": [],
           "channel_type": ["1_垂类", "1_重点垂类", "2_情感幽默"], "generate_keys": [["grade", "D", 21]], "limit_position": 31,
           "final_pos": 50, "hot_ext": "vcnt:1", "social_flag": 0, "reasons": [],
           "source_details": "s1k0:gra_D:o_58:lpo_31:fpo_50"},
          {"query": "冲绳县首次启动土壤和水体调查", "score": 0.04197916, "flag": 0, "topic_flag": 1, "hot": 718134,
           "description": 23773, "ori_pos": 59, "cate": ["社会新闻"], "sub_category": [""], "star_name": [],
           "event_name": [], "channel_type": ["1_社会", "3_权威媒体主持"], "generate_keys": [["grade", "A", 21]],
           "limit_position": 21, "final_pos": 51, "hot_ext": "vcnt:1", "social_flag": 0, "social_tag": 1, "reasons": [],
           "source_details": "s1k0:gra_A:o_59:lpo_21:fpo_51"},
          {"query": "日本国内超市停买水产品让日企心态崩了", "score": 0.041915423109000004, "flag": 16, "topic_flag": 1, "hot": 595605,
           "description": "昨晚霸榜",
           "generate_keys": [["expose_reduce", 0.5817, 16, [3, 4, 3]], ["grade", "A", 1], ["redis_top_pos", 1, 2]],
           "ori_pos": 60, "cate": ["社会新闻"], "sub_category": [""], "star_name": [], "event_name": [],
           "channel_type": ["1_社会", "3_权威媒体主持"], "limit_position": 2, "final_pos": 52, "hot_ext": "vcnt:1",
           "source_flag": "1", "social_flag": 0, "social_tag": 1, "reasons": [],
           "source_details": "s0k12:s1k0:gra_A:o_60:lpo_2:fpo_52"},
          {"query": "女生橘子洲头唱灯火里的中国获赞百万", "score": 0.041726865, "flag": 0, "topic_flag": 1, "hot": 448517,
           "description": 22971, "ori_pos": 61, "cate": ["社会新闻"], "sub_category": [""], "star_name": [],
           "event_name": [], "channel_type": ["1_社会", "3_权威媒体主持"], "generate_keys": [["grade", "D", 21]],
           "limit_position": 31, "final_pos": 53, "hot_ext": "vcnt:1", "social_flag": 0, "reasons": [],
           "source_details": "s0k12:s1k0:gra_D:o_61:lpo_31:fpo_53"},
          {"query": "中国地理评出一生最值得去的20个地方", "score": 0.0415714235646, "flag": 0, "topic_flag": 0, "hot": 855879,
           "description": 21787,
           "generate_keys": [["expose_reduce", 0.6982, 29, [8, 8]], ["grade", "A", 1], ["top10_hot_limit", 11],
                             ["redis_top_pos", 11, 21]], "ori_pos": 62, "cate": ["旅游"], "sub_category": [""],
           "star_name": [], "event_name": [], "channel_type": ["1_垂类", "1_重点垂类", "3_单条", "4_单条视频作品"],
           "limit_position": 21, "final_pos": 54, "hot_ext": "vcnt:1", "social_flag": 0, "social_tag": 4, "reasons": [],
           "source_details": "s0k12:s1k0:gra_A:o_62:lpo_21:fpo_54"},
          {"query": "当代大学宿舍能有多简陋", "score": 0.040809948, "flag": 0, "topic_flag": 1, "hot": 856062,
           "description": 29429, "ori_pos": 63, "cate": ["情感"], "sub_category": [""], "star_name": [], "event_name": [],
           "channel_type": ["1_垂类", "1_重点垂类", "2_情感幽默"], "generate_keys": [["grade", "C", 21]], "limit_position": 21,
           "final_pos": 55, "hot_ext": "vcnt:1", "social_flag": 0, "reasons": [],
           "source_details": "s1k0:gra_C:o_63:lpo_21:fpo_55"},
          {"query": "家长吐槽恶改版儿歌教小孩说脏话", "score": 0.039756022, "flag": 0, "topic_flag": 1, "hot": 302986,
           "description": 29513, "ori_pos": 64, "cate": ["社会新闻"], "sub_category": [""], "star_name": [],
           "event_name": [], "channel_type": ["1_社会", "3_权威媒体主持"], "generate_keys": [["grade", "C", 21]],
           "limit_position": 21, "final_pos": 56, "hot_ext": "vcnt:1", "social_flag": 0, "social_tag": 3, "reasons": [],
           "source_details": "s1k0:gra_C:o_64:lpo_21:fpo_56"},
          {"query": "檀健次 帕拉丁", "score": 0.0396850005, "flag": 1, "topic_flag": 0, "hot": 296782, "description": 302144,
           "ori_pos": 65, "cate": ["艺人"], "sub_category": ["艺人", "艺人新闻"], "star_name": ["檀健次"], "event_name": [],
           "channel_type": ["1_文娱"], "generate_keys": [["grade", "C", 1]], "limit_position": 11, "final_pos": 57,
           "hot_ext": "vcnt:1", "social_flag": 0, "reasons": [], "source_details": "s1k0:gra_C:o_65:lpo_11:fpo_57"},
          {"query": "中学生参观博物馆指出错误获表扬", "score": 0.039465144, "flag": 32768, "topic_flag": 1, "hot": 608917,
           "description": 93341, "ori_pos": 66, "cate": ["社会新闻"], "sub_category": [""], "star_name": [],
           "event_name": [], "channel_type": ["1_社会", "3_暖新闻", "3_权威媒体主持"],
           "generate_keys": [["grade", "A", 1], ["redis_top_pos", 1, 11]], "limit_position": 11, "final_pos": 58,
           "hot_ext": "vcnt:1", "social_flag": 0, "reasons": [], "source_details": "s1k0:gra_A:o_66:lpo_11:fpo_58"},
          {"query": "油炸炒饭汉堡包", "score": 0.03932435, "flag": 0, "topic_flag": 0, "hot": 792666, "description": 35556,
           "ori_pos": 69, "cate": ["美食"], "sub_category": [""], "star_name": [], "event_name": [],
           "channel_type": ["1_垂类", "1_重点垂类", "3_单条", "4_单条视频作品"], "generate_keys": [["grade", "C", 21]],
           "limit_position": 21, "final_pos": 59, "hot_ext": "vcnt:1", "social_flag": 0, "reasons": [],
           "source_details": "s1k0:gra_C:o_69:lpo_21:fpo_59"},
          {"query": "陈晓吻戏从脸红到耳朵", "score": 0.03862792, "flag": 1, "topic_flag": 1, "hot": 283111, "description": 286273,
           "ori_pos": 70, "cate": ["影视"], "sub_category": ["影视", "明星影视"], "star_name": ["娜扎", "陈晓"], "event_name": [],
           "channel_type": ["1_文娱"],
           "generate_keys": [["grade", "C", 1], ["toplimit_Enter", 815], ["hot_top10_keep", 720],
                             ["toplimit_Enter", 820], ["toplimit_Enter", 825], ["toplimit_Enter", 830]],
           "limit_position": 11, "ctg_control_type_list": [815, 820, 825, 830], "category_control_type": 830,
           "final_pos": 60, "hot_ext": "vcnt:1", "social_flag": 0, "reasons": [],
           "source_details": "s0k12:s1k0:gra_C:tl_e_815:tl_e_820:tl_e_825:tl_e_830:o_70:lpo_11:fpo_60"}]

clicked = ["山西致5死27伤旅游大巴事故监控曝光", "孟美岐空中坠落", "刀郎发微博了", "福岛真相"]

for idx, info in enumerate(result):
    if info["query"] in clicked:
        print(idx, info["query"])



d = {}

d["2"]=2
d["1"]=1
d["3"]=3

for k,v in d.items():
    print(k,v)